[project]
name = "collateral-simulator"
authors = ["Stacks Developer"]
description = "Digital asset collateralization and risk management smart contract system"
telemetry = false
requirements = []

[contracts.asset-registry]
path = "contracts/asset-registry.clar"
depends_on = []

[contracts.collateral-tracker]
path = "contracts/collateral-tracker.clar"
depends_on = []

[contracts.risk-evaluator]
path = "contracts/risk-evaluator.clar"
depends_on = []

[contracts.liquidation-manager]
path = "contracts/liquidation-manager.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
